import type { LeadContext } from "./tipos";

export function criarContextoInicial(): LeadContext {
  return {
    tipoLead: null,
    cidade: null,
    bairro: null,
    tipoImovel: null,
    quartos: null,
    banheiros: null,
    areaM2: null,
    valor: null,
    pet: null,
    financiamento: null,
    fgts: null,
    urgencia: null,
    objetivo: null,
    origem: null,
    canal: null,
    prazoMudanca: null,
    documentacao: null,
    documentacaoObservacao: null,
    entradaDisponivel: null,
    garagem: null,
    vagas: null,
    condominioAceita: null,
    prazoCompra: null,
    valorEsperado: null,
    motivoVenda: null,
    imovelFinanciado: null,
    imovelOcupado: null,
    jaAnunciou: null,
    exclusividade: null,
    moradores: null,
    alugado: null,
    valorAluguelAtual: null,
    condominioValor: null,
    iptu: null,
    administracaoAtual: null,
    motivoTroca: null,
    administracaoCompleta: null,
    chavesDisponiveis: null,
    destinoCaptacao: null,
    especialistaAtivo: null,
    handoffReady: false,
    ultimaPerguntaCampo: null,
  };
}
