"use client";
import { useActionState, useState } from "react";
import { type SafeUserAccess } from "../../../../lib/admin/access/contracts";
import { salvarUsuarioAcesso, type UserAccessActionState } from "./actions";
export function UserAccessForm({ user, people, currentUserId }: { user: SafeUserAccess; people: { id: string; nome: string }[]; currentUserId: string }) {
  const [open, setOpen] = useState(false); const [state, action, pending] = useActionState(salvarUsuarioAcesso, { status: "idle" } satisfies UserAccessActionState);
  const self = user.user_id === currentUserId;
  return <div className="rounded-2xl border border-[#E8DDCB] bg-white p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold text-[#071E36]">{user.email ?? "Usuário sem e-mail"}</p><p className="text-xs text-[#64736D]">{user.papel ?? "Aguardando configuração"} · {user.ativo ? "Acesso ativo" : user.papel ? "Acesso inativo" : "Aguardando configuração"}</p></div><button type="button" onClick={() => setOpen((v) => !v)} className="rounded-lg border px-3 py-2 text-sm">{open ? "Fechar" : "Configurar"}</button></div>{open ? <form action={action} className="mt-4"><fieldset disabled={pending} className="grid gap-3 sm:grid-cols-3"><input type="hidden" name="user_id" value={user.user_id}/><input type="hidden" name="updated_at_esperado" value={user.perfil_updated_at ?? ""}/><label className="grid gap-1 text-sm">Papel<select name="papel" defaultValue={user.papel ?? "atendimento"} disabled={self && user.papel === "administrador"}><option value="administrador">Administrador</option><option value="gestor">Gestor</option><option value="corretor">Corretor</option><option value="atendimento">Atendimento</option></select></label><label className="flex items-center gap-2 text-sm"><input type="hidden" name="ativo" value="false"/><input type="checkbox" name="ativo" value="true" defaultChecked={user.ativo === true} disabled={self}/> Acesso ativo</label><label className="grid gap-1 text-sm">Pessoa vinculada<select name="pessoa_id" defaultValue={user.pessoa_id ?? ""}><option value="">Sem Pessoa</option>{people.map((p) => <option key={p.id} value={p.id}>{p.nome}</option>)}</select></label></fieldset>{state.message ? <p role="alert" className="mt-3 text-sm text-[#8a2e1c]">{state.message}</p> : null}<button type="submit" disabled={pending} className="mt-4 rounded-lg bg-[#071E36] px-4 py-2 text-sm font-semibold text-white">{pending ? "Salvando..." : "Salvar acesso"}</button></form> : null}</div>;
}
