import type { UCEAcademyScenario } from "../core/types";

export const uceAcademyScenarios: UCEAcademyScenario[] = [
  {
    id: "inquilino_urgente",
    title: "Inquilino urgente",
    description: "Lead precisa mudar rapidamente e exige velocidade de conversao.",
    leadType: "inquilino",
    startingMessage: "Preciso alugar apartamento na Jatiuca antes de julho.",
    expectedFields: ["objetivo", "cidade", "bairro", "tipoImovel", "urgencia"],
    expectedStrategy: "modo_conversao",
    expectedRisks: ["prazo curto"],
    expectedHandoff: "Enviar opcoes aderentes e tentar visita imediata.",
  },
  {
    id: "inquilino_sem_pressa",
    title: "Inquilino sem pressa",
    description: "Lead pesquisando, ideal para abordagem consultiva.",
    leadType: "inquilino",
    startingMessage: "Estou so pesquisando apartamentos em Maceio.",
    expectedFields: ["objetivo", "cidade", "tipoImovel"],
    expectedStrategy: "modo_consultivo",
    expectedRisks: ["baixa urgencia"],
    expectedHandoff: "Criar confianca e enviar curadoria.",
  },
  {
    id: "proprietario_administracao",
    title: "Proprietario administracao",
    description: "Proprietario quer seguranca para locar e administrar.",
    leadType: "proprietario",
    startingMessage: "Quero administrar meu imovel para locacao.",
    expectedFields: ["objetivo", "tipoImovel"],
    expectedStrategy: "modo_administracao",
    expectedRisks: ["garantia", "inquilino"],
    expectedHandoff: "Acionar especialista de administracao.",
  },
  {
    id: "comprador_financiado",
    title: "Comprador financiado",
    description: "Comprador com financiamento e necessidade de qualificacao financeira.",
    leadType: "comprador",
    startingMessage: "Quero comprar apartamento financiado usando FGTS.",
    expectedFields: ["objetivo", "tipoImovel", "financiamento", "fgts"],
    expectedStrategy: "modo_consultivo",
    expectedRisks: ["credito"],
    expectedHandoff: "Validar credito e faixa de valor.",
  },
  {
    id: "investidor",
    title: "Investidor",
    description: "Lead com foco patrimonial e retorno.",
    leadType: "comprador",
    startingMessage: "Procuro imovel para investimento e renda.",
    expectedFields: ["objetivo"],
    expectedStrategy: "modo_investidor",
    expectedRisks: ["retorno", "liquidez"],
    expectedHandoff: "Mapear retorno esperado e perfil de risco.",
  },
  {
    id: "lead_com_objecao_preco",
    title: "Lead com objecao de preco",
    description: "Lead sinaliza resistencia financeira.",
    leadType: "inquilino",
    startingMessage: "Achei caro, esse aluguel passa do que eu esperava.",
    expectedFields: ["valor"],
    expectedStrategy: "modo_consultivo",
    expectedRisks: ["preco"],
    expectedHandoff: "Reenquadrar valor e comparar custo-beneficio.",
  },
  {
    id: "lead_com_objecao_fiador",
    title: "Lead com objecao de fiador",
    description: "Lead precisa alternativa de garantia.",
    leadType: "inquilino",
    startingMessage: "Nao tenho fiador, consigo alugar mesmo assim?",
    expectedFields: ["documentacao"],
    expectedStrategy: "modo_juridico_cauteloso",
    expectedRisks: ["garantia", "documentacao"],
    expectedHandoff: "Explicar alternativas e acionar corretor.",
  },
  {
    id: "alto_padrao",
    title: "Alto padrao",
    description: "Lead premium exige curadoria e discricao.",
    leadType: "inquilino",
    startingMessage: "Quero apartamento acima de 8 mil na Ponta Verde.",
    expectedFields: ["objetivo", "tipoImovel", "valor", "bairro"],
    expectedStrategy: "modo_alto_padrao",
    expectedRisks: ["alta expectativa"],
    expectedHandoff: "Atendimento personalizado e selecao premium.",
  },
];
