import type { UCEMatchEntity } from "./types";

export const demoMatchEntities: UCEMatchEntity[] = [
  {
    id: "imovel-ponta-verde-3q-650k",
    type: "imovel",
    label: "Apartamento 3 quartos na Ponta Verde",
    cidade: "Maceio",
    bairro: "Ponta Verde",
    tipoImovel: "apartamento",
    valor: 650000,
    areaM2: 92,
    quartos: 3,
    banheiros: 2,
    vagas: 2,
    pet: true,
    objetivo: "venda",
    financiamento: true,
    perfil: "familiar",
    proprietarioId: "proprietario-ponta-verde",
  },
  {
    id: "imovel-serraria-locacao-3500",
    type: "imovel",
    label: "Apartamento familiar na Serraria",
    cidade: "Maceio",
    bairro: "Serraria",
    tipoImovel: "apartamento",
    valor: 3500,
    areaM2: 80,
    quartos: 3,
    banheiros: 2,
    vagas: 1,
    pet: false,
    objetivo: "locacao",
    perfil: "familiar",
    proprietarioId: "proprietario-serraria",
  },
  {
    id: "comprador-financiado-ponta-verde",
    type: "comprador",
    label: "Comprador financiado para apartamento na orla",
    cidade: "Maceio",
    bairro: "Ponta Verde",
    tipoImovel: "apartamento",
    valor: 700000,
    quartos: 3,
    vagas: 2,
    objetivo: "compra",
    financiamento: true,
    fgts: true,
    perfil: "familiar",
    urgencia: "media",
  },
  {
    id: "inquilino-serraria-3q",
    type: "inquilino",
    label: "Inquilino busca 3 quartos na Serraria",
    cidade: "Maceio",
    bairro: "Serraria",
    tipoImovel: "apartamento",
    valor: 3600,
    quartos: 3,
    vagas: 1,
    pet: false,
    objetivo: "locacao",
    perfil: "familiar",
    urgencia: "baixa",
  },
  {
    id: "proprietario-farol-administracao",
    type: "proprietario",
    label: "Proprietario com apartamento no Farol",
    cidade: "Maceio",
    bairro: "Farol",
    tipoImovel: "apartamento",
    valor: 3200,
    quartos: 3,
    vagas: 1,
    objetivo: "administracao",
    perfil: "familiar",
  },
];
