import type { UCEConhecimentoItem } from "./types";

export const conhecimentoItems: UCEConhecimentoItem[] = [
  {
    id: "institucional-terrazza-atuacao",
    titulo: "Terrazza Solucoes Imobiliarias",
    categoria: "institucional",
    dominio: "Institucional",
    conteudo:
      "A Terrazza atua com solucoes imobiliarias em Maceio e Aracaju, com foco em locacao, administracao, captacao e venda conforme a praca.",
    tags: ["terrazza", "maceio", "aracaju", "locacao", "administracao", "venda"],
    prioridade: 80,
    relacionamentos: ["Maceio", "Aracaju", "Locacao", "Administracao", "Venda"],
    fonte: { id: "uce-interno", nome: "Base interna UCE", tipo: "base_interna" },
    cidade: "Maceio",
    estado: "AL",
    vigencia: "permanente",
  },
  {
    id: "garantias-seguro-fianca-maximiza",
    titulo: "Seguro Fianca e analise Maximiza",
    categoria: "garantias",
    dominio: "Garantias",
    conteudo:
      "Seguro fianca e uma alternativa de garantia locaticia que depende de analise cadastral. A UCE nao deve prometer aprovacao.",
    tags: ["seguro fianca", "garantias", "locacao", "maximiza", "analise cadastral"],
    prioridade: 95,
    relacionamentos: ["Seguro Fianca", "Garantias", "Locacao", "Maximiza", "Analise cadastral"],
    fonte: { id: "uce-garantias", nome: "Base de garantias", tipo: "manual" },
    vigencia: "operacional",
  },
  {
    id: "bairro-ponta-verde-mercado",
    titulo: "Ponta Verde: perfil comercial",
    categoria: "bairros",
    dominio: "Bairros",
    conteudo:
      "Ponta Verde tem forte demanda residencial, turistica e de alto padrao, com boa aderencia para venda, locacao e temporada.",
    tags: ["ponta verde", "maceio", "turismo", "airbnb", "alto padrao", "venda", "locacao"],
    prioridade: 90,
    relacionamentos: ["Ponta Verde", "Maceio", "Turismo", "Airbnb", "Alto padrao", "Venda", "Locacao"],
    fonte: { id: "territorial-maceio", nome: "Base territorial Maceio", tipo: "manual" },
    cidade: "Maceio",
    estado: "AL",
    bairro: "Ponta Verde",
    vigencia: "mercado_atual",
  },
  {
    id: "locacao-condominio-garantias",
    titulo: "Locacao: condominio, garantias e perfil do inquilino",
    categoria: "locacao",
    dominio: "Locacao",
    conteudo:
      "Na locacao, a UCE deve entender perfil do inquilino, valor, bairro, pet, urgencia, condominio e garantia disponivel.",
    tags: ["locacao", "inquilino", "condominio", "garantias", "pet", "bairro"],
    prioridade: 88,
    relacionamentos: ["Locacao", "Garantias", "Condominio", "Bairros"],
    fonte: { id: "uce-locacao", nome: "Base de locacao", tipo: "manual" },
    vigencia: "operacional",
  },
  {
    id: "venda-avaliacao-documentacao",
    titulo: "Venda: avaliacao comercial e documentacao",
    categoria: "venda",
    dominio: "Venda",
    conteudo:
      "Na venda, a UCE deve organizar captacao, avaliacao comercial, documentacao, matricula, preco, negociacao e proposta.",
    tags: ["venda", "avaliacao", "documentacao", "matricula", "preco", "captacao"],
    prioridade: 88,
    relacionamentos: ["Venda", "Mercado", "Imoveis", "Documentacao"],
    fonte: { id: "uce-venda", nome: "Base de venda", tipo: "manual" },
    vigencia: "operacional",
  },
  {
    id: "administracao-manutencao-condominio",
    titulo: "Administracao: manutencao, repasse e suporte",
    categoria: "administracao",
    dominio: "Administracao",
    conteudo:
      "Na administracao, a UCE deve considerar divulgacao, contrato, vistoria, cobranca, repasse, manutencao, condominio e suporte ao proprietario.",
    tags: ["administracao", "manutencao", "repasse", "condominio", "proprietario", "vistoria"],
    prioridade: 90,
    relacionamentos: ["Administracao", "Condominio", "Manutencao", "Juridico"],
    fonte: { id: "uce-administracao", nome: "Base de administracao", tipo: "manual" },
    vigencia: "operacional",
  },
  {
    id: "juridico-limites-atendimento",
    titulo: "Limites juridicos do atendimento UCE",
    categoria: "juridico",
    dominio: "Juridico",
    conteudo:
      "A UCE nao deve dar parecer juridico definitivo. Deve orientar encaminhamento para especialista quando houver risco documental, conflito ou duvida juridica.",
    tags: ["juridico", "lgpd", "documentacao", "conflito", "especialista"],
    prioridade: 100,
    relacionamentos: ["Juridico", "Documentacao", "Conflito", "Administracao"],
    fonte: { id: "uce-juridico", nome: "Base juridica basica", tipo: "manual" },
    vigencia: "permanente",
  },
  {
    id: "financiamento-fgts-compra",
    titulo: "Compra com financiamento e FGTS",
    categoria: "financiamento",
    dominio: "Financiamento",
    conteudo:
      "Para compradores, a UCE deve identificar se havera financiamento, entrada disponivel e uso de FGTS, sem prometer aprovacao de credito.",
    tags: ["compra", "financiamento", "fgts", "entrada", "credito"],
    prioridade: 85,
    relacionamentos: ["Financiamento", "Venda", "Comprador", "Mercado"],
    fonte: { id: "uce-financiamento", nome: "Base de financiamento", tipo: "manual" },
    vigencia: "operacional",
  },
];
